//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.42000
//


/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="webserviceSoap", Namespace="http://tempuri.org/")]
public partial class webservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback DBLookUpStammdatenOperationCompleted;
    
    /// CodeRemarks
    public webservice() {
        this.Url = "http://127.0.0.1:8080/webservice.asmx";
    }
    
    /// CodeRemarks
    public event DBLookUpStammdatenCompletedEventHandler DBLookUpStammdatenCompleted;
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DBLookUpStammdaten", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Stammdaten DBLookUpStammdaten(int id) {
        object[] results = this.Invoke("DBLookUpStammdaten", new object[] {
                    id});
        return ((Stammdaten)(results[0]));
    }
    
    /// CodeRemarks
    public void DBLookUpStammdatenAsync(int id) {
        this.DBLookUpStammdatenAsync(id, null);
    }
    
    /// CodeRemarks
    public void DBLookUpStammdatenAsync(int id, object userState) {
        if ((this.DBLookUpStammdatenOperationCompleted == null)) {
            this.DBLookUpStammdatenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDBLookUpStammdatenOperationCompleted);
        }
        this.InvokeAsync("DBLookUpStammdaten", new object[] {
                    id}, this.DBLookUpStammdatenOperationCompleted, userState);
    }
    
    private void OnDBLookUpStammdatenOperationCompleted(object arg) {
        if ((this.DBLookUpStammdatenCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DBLookUpStammdatenCompleted(this, new DBLookUpStammdatenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Stammdaten {
    
    private int personalNrField;
    
    private string vornameField;
    
    private string nameField;
    
    private string abteilungField;
    
    private int abteilungsNrField;
    
    private Leistung[] leistungenField;
    
    /// <remarks/>
    public int PersonalNr {
        get {
            return this.personalNrField;
        }
        set {
            this.personalNrField = value;
        }
    }
    
    /// <remarks/>
    public string Vorname {
        get {
            return this.vornameField;
        }
        set {
            this.vornameField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Abteilung {
        get {
            return this.abteilungField;
        }
        set {
            this.abteilungField = value;
        }
    }
    
    /// <remarks/>
    public int AbteilungsNr {
        get {
            return this.abteilungsNrField;
        }
        set {
            this.abteilungsNrField = value;
        }
    }
    
    /// <remarks/>
    public Leistung[] Leistungen {
        get {
            return this.leistungenField;
        }
        set {
            this.leistungenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Leistung {
    
    private int localLeistungsNrField;
    
    private int remoteLeistungsNrField;
    
    private int vorgangNrField;
    
    private int personalNrField;
    
    private System.DateTime datumField;
    
    private float stundenleistungField;
    
    private float erzielterFortschrittField;
    
    private System.DateTime buchungsdatumField;
    
    private Vorgang vorgangField;
    
    private Stammdaten stammdatenField;
    
    /// <remarks/>
    public int LocalLeistungsNr {
        get {
            return this.localLeistungsNrField;
        }
        set {
            this.localLeistungsNrField = value;
        }
    }
    
    /// <remarks/>
    public int RemoteLeistungsNr {
        get {
            return this.remoteLeistungsNrField;
        }
        set {
            this.remoteLeistungsNrField = value;
        }
    }
    
    /// <remarks/>
    public int VorgangNr {
        get {
            return this.vorgangNrField;
        }
        set {
            this.vorgangNrField = value;
        }
    }
    
    /// <remarks/>
    public int PersonalNr {
        get {
            return this.personalNrField;
        }
        set {
            this.personalNrField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    public float Stundenleistung {
        get {
            return this.stundenleistungField;
        }
        set {
            this.stundenleistungField = value;
        }
    }
    
    /// <remarks/>
    public float ErzielterFortschritt {
        get {
            return this.erzielterFortschrittField;
        }
        set {
            this.erzielterFortschrittField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Buchungsdatum {
        get {
            return this.buchungsdatumField;
        }
        set {
            this.buchungsdatumField = value;
        }
    }
    
    /// <remarks/>
    public Vorgang Vorgang {
        get {
            return this.vorgangField;
        }
        set {
            this.vorgangField = value;
        }
    }
    
    /// <remarks/>
    public Stammdaten Stammdaten {
        get {
            return this.stammdatenField;
        }
        set {
            this.stammdatenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Vorgang {
    
    private int vorgangNrField;
    
    private string projektElementBeschreibungField;
    
    private string projektField;
    
    private int statusField;
    
    private string prozessElementBeschreibungField;
    
    private Leistung[] leistungenField;
    
    /// <remarks/>
    public int VorgangNr {
        get {
            return this.vorgangNrField;
        }
        set {
            this.vorgangNrField = value;
        }
    }
    
    /// <remarks/>
    public string ProjektElementBeschreibung {
        get {
            return this.projektElementBeschreibungField;
        }
        set {
            this.projektElementBeschreibungField = value;
        }
    }
    
    /// <remarks/>
    public string Projekt {
        get {
            return this.projektField;
        }
        set {
            this.projektField = value;
        }
    }
    
    /// <remarks/>
    public int Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string ProzessElementBeschreibung {
        get {
            return this.prozessElementBeschreibungField;
        }
        set {
            this.prozessElementBeschreibungField = value;
        }
    }
    
    /// <remarks/>
    public Leistung[] Leistungen {
        get {
            return this.leistungenField;
        }
        set {
            this.leistungenField = value;
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void DBLookUpStammdatenCompletedEventHandler(object sender, DBLookUpStammdatenCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DBLookUpStammdatenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DBLookUpStammdatenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public Stammdaten Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Stammdaten)(this.results[0]));
        }
    }
}
